# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 04:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=45)),
                ('quoted_by', models.CharField(blank=True, max_length=30)),
                ('created_by', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            managers=[
                ('QuoteManager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('username', models.CharField(max_length=45)),
                ('email', models.CharField(blank=True, max_length=60)),
                ('password', models.CharField(max_length=45)),
                ('date', models.CharField(max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            managers=[
                ('UserManager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='quotes',
            name='owned_by',
            field=models.ManyToManyField(blank=True, to='wish.Users'),
        ),
    ]
